# Generated by Django 4.2.7 on 2023-12-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8)),
                ('full_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MainApp.snippet'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MainApp.language'),
        ),
    ]
